config/adminlte.php, resources/views/page.blade.php, resources/views/partials/menu-item.blade.php
Added the option to the menu config for using submenu as a multilevel menu item. Also made a small change that the url option is no longer throwing an error when left out, not specifying an url will return a #.
=> Add multilevel menu

composer.json
A simple change to allow for support for Laravel 5.3.
=> Add Support for laravel 5.3

resources/views/partials/menu-item-top-nav.blade.php, resources/views/partials/menu-item.blade.php
#14 
Added working active menus for top-nav layout, but the sidebar layout for some reason does nothing.
Note that this is extremely wonky and doesn't account for dynamically generated URL. Only the URLs specified in the adminlte.php in the config folder are going to have an active class.
If all URLs were to be converted to routes, it would be a bit easier. But then again, you can just add [this package](https://github.com/laravelista/Ekko) for that.
=> Sort of add working active classes

resources/lang/de/adminlte.php
Hello,
thanks for the nice package!
I have added a language file for german in this pull request.
=> Added german translation

resources/lang/es/adminlte.php, resources/lang/pt-br/adminlte.php
Support for Portuguese and Spanish available out of the box.
=> Translations to brazilian portuguese and spanish

README.md, resources/lang/es/adminlte.php
=> #Fix es/adminlte.php

resources/views/master.blade.php
Use bootstrap style istand of default for more fluidity in desing.
=> Use datatables with bootstrap styles

resources/views/master.blade.php
Never a bad thing to keep up with the latest dependency versions I think
=> Update datatables to 1.10.15 from 1.10.13

README.md, composer.json
I added 5.5 support and package autodiscovery by modifying composer.json. At first glance there seem to be no breaking changes on Laravel 5.5.
=> Laravel 5.5 package autodiscovery

resources/lang/cn/adminlte.php
hi, thank you for your awesome integration of Laravel & AdminLTE. It works fine in my project.
Here is the simplified Chinese translation for Laravel-AdminLTE.
Heaps thanks
=> add simplified Chinese lang translation

README.md, src/Menu/Filters/GateFilter.php
Pass a model to the Gate for authorizing actions.
**Larvel Documentation:**
```php
if (Gate::allows('update', $model)) {
// The current user can update the post...
}
```
**Usage:**
```php
$event->menu->add([
'header' => 'HEADER', 
'can' => 'update',
'model' => $model
]);
```
closes #125
=> Add model support to Menu GateFilter

config/adminlte.php
One spelling mistake (ligth) and one extra word (and).
=> Ran spellcheck on adminlte.php

README.md, config/adminlte.php, resources/lang/de/menu.php, resources/lang/en/menu.php, resources/lang/pt-br/menu.php, resources/views/partials/menu-item-top-nav.blade.php, resources/views/partials/menu-item.blade.php, src/Menu/Filters/LangFilter.php, tests/Menu/BuilderTest.php, tests/TestCase.php
Thank you very much @Anpix (https://github.com/jeroennoten/Laravel-AdminLTE/pull/63) and @zcwilt (https://github.com/jeroennoten/Laravel-AdminLTE/pull/116) for the great work!
=> Add menu translator

resources/assets/dist/css/skins/skin-blue.css, src/Menu/ActiveChecker.php, src/Menu/Filters/ClassesFilter.php, src/Menu/Filters/SubmenuFilter.php, tests/TestCase.php
Addresses issue #124 
@jeroennoten : as an example, I also added some styling tweaks to the default skin. You may want to redo this on your css preprocessor and recompile/minify
=> Fixed sidebar submenu active check

resources/views/page.blade.php
I did noticed that the admin-lte page doesn't have a footer, so i put a @yield('footer') on page.blade.php. This way i can create my on footer on my admin-lte page.
I hope this helps.
=> Add footer at page.blade.php

config/adminlte.php, resources/views/page.blade.php, resources/views/partials/menu-item-top-nav.blade.php, resources/views/partials/menu-item.blade.php
https://github.com/jeroennoten/Laravel-AdminLTE/issues/318
https://github.com/jeroennoten/Laravel-AdminLTE/issues/317
=> fix menu errors

resources/views/partials/menu-item-top-nav.blade.php, resources/views/partials/menu-item.blade.php
- fixed search form error
- corrected fontawesome classes
- fixed CI
- fixed top-nav item title's
=> menu fixes

resources/lang/tr/adminlte.php, resources/lang/tr/menu.php
Hello,
First of all, thanks for making this package available for the community. This made implementation of AdminLTE with Laravel quite effortlessly.
You can find the Turkish translation of the resources at this pull request.
Thanks again,
=> Turkish translations added

config/adminlte.php, resources/views/page.blade.php
* Enable / Disable Sidebar
* Theme (dark/light)
* Custom Hide/Show Icon
=> Add Control Sidebar (Right Sidebar)

config/adminlte.php
=> update cdn sweetalert2

src/Menu/Filters/LangFilter.php
Fix Trans Error
* 5.8 and lower keeps working
Issue #354
=> Fix Trans Error

README.md, resources/views/login.blade.php, src/AdminLteServiceProvider.php
* Readme upgrade guide updated
* ServiceProvider file publish location fixed
* Login.blade - Was trying to change glyphicons to fontawesome. Removed changes while they aren't ok.
=> Readme Upgrade guide with a little more info

README.md
Better categorized explanation since we are having some installations issues.
=> Fixing Readme missguiding

resources/views/page.blade.php
The header tag is closed but not opened
=> Add missing header tag

composer.json
Laravel require fix
>=6.0.0 <7.0.0
was 
>=6.0.0 < 6.1
=> Laravel 6.1 compatibility fix

README.md, config/adminlte.php, resources/lang/de/menu.php, resources/lang/en/menu.php, resources/views/master.blade.php, resources/views/page.blade.php, resources/views/passwords/confirm.blade.php, src/Console/AdminLteInstallCommand.php, src/Menu/Filters/LangFilter.php
- some little adminlte:install changes
- enabled recursive for some assets
- added checkup if basic_routes already added to avoid duplicate lines
- fixed --with description with main_views
- enhanced master & page view
- added laravel mix option
- added ability to collapse sidebar via blade files
- updated config/adminlte
- updated readme according to the laravel mix option
- added passwords/confirm view & fixed a error in page.blade
=> some little fixes & enhancements

README.md
ServiceProvider instead of AdminLteServiceProvider in v1
=> Fix customize views command

src/Menu/Filters/HrefFilter.php
Now developers can use the adminlte menu to route the parameters they have to give.
Example;
```
...
[
'text'  => 'Profile',
'route' => ['users.show', session('user_id')],
'icon'  => 'fas fa-fw fa-user'
],
...
```
=> Parameter send support is added to route function.

resources/lang/en/adminlte.php, resources/views/login.blade.php, resources/views/master.blade.php, resources/views/page.blade.php, resources/views/passwords/confirm.blade.php, resources/views/passwords/email.blade.php, resources/views/passwords/reset.blade.php, resources/views/register.blade.php, resources/views/verify.blade.php, src/AdminLteServiceProvider.php, src/Console/AdminLteInstallCommand.php
- replaced misplaced null coalescing operator in views
- removed unnecessary view load fallback 
- added adminlte_css_pre yield in master.blade.php 
- fixed icheck bootstrap color override in login.blade
- moved icheck bootstrap in adminlte_css_pre
- updated adminlte_css section in register.blade and login.blade like its in page.blade
- added verify view
- created verify lang strings
- created verify.blade.php
- updated AdminLteInstallCommand with verify extend view
I've updated the english (en) lang file but the other will need also updated with the new translated lang stings.
=> some further enhancements & fixes

resources/views/login.blade.php, resources/views/passwords/confirm.blade.php, resources/views/passwords/email.blade.php, resources/views/passwords/reset.blade.php, resources/views/register.blade.php, src/Console/AdminLtePluginCommand.php
- added missing plugins in adminlte:plugins command 
- added autofocus on first input in auth views
=> small enhancements

src/Console/AdminLteStatusCommand.php
=> fixed auth view checkup if no files exists

resources/lang/de/adminlte.php
I've added the verification text in german, cause this was missing, in this language.
=> added verification text in german

README.md, resources/lang/tr/adminlte.php, resources/lang/tr/menu.php
Hey there,
In this pull request, I've updated Turkish translations for the new major version, also fixed a typo in Readme.
Thanks, and Happy New Year / Merry Christmas!
=> Turkish translations updated.

README.md, config/adminlte.php, resources/views/master.blade.php
It brings the possibility to use favicons easily.
PR to fix #436
=> added favicon possibility

resources/lang/ru/menu.php, resources/lang/uk/menu.php
Translations for Main Navigation (russian and ukrainian languages)
=> Added translation for Menu (ru and uk)

resources/views/partials/menu-item.blade.php
implement parameter called shift to shift item on submenu. Now is possible shift items of submenu informing bootstrap classes ml-0 to ml-6 in config/adminlte.php.
=> implement parameter shift to left shift item on submenu

resources/views/master.blade.php
=> Add locale master

resources/views/master.blade.php
CSRF is added by default in the master.blade.php template.
=> CSRF is added

README.md, config/adminlte.php, resources/views/page.blade.php, resources/views/partials/menu-item-top-nav-left.blade.php, resources/views/partials/menu-item-top-nav-right.blade.php, resources/views/partials/menu-item-top-nav-user.blade.php, resources/views/partials/menu-item-top-nav.blade.php, resources/views/partials/menu-item.blade.php, resources/views/passwords/confirm.blade.php, src/AdminLte.php, src/Menu/Builder.php, src/Menu/Filters/SearchFilter.php, tests/Menu/BuilderTest.php, tests/ServiceProviderTest.php
- enhanced Builder with findItem, addAfter, addBefore, addIn & remove (#475 & possible #468)
- fixed navbar class for topnav only (#447)
- enhanced topnav
- added user menu incl. header, image and description 
- added `topnav_right` & `topnav_user` option like topnav option menu to place menu items in right sided nav and user menu nav.
- fixed SearchFilter to allow uppercase methods	(#461)
- fixed search input docs failure (#459)
- updated brand-image with dynamic class via logo_img_class (#440)
I need to test some stuff and fix the tests, then I open the PR 😄 may I'll fix some other issues too in this PR.
Todo
You can place almost everywhere a new menu item via the MenuBuilder.
To get a dynamic item placing you can add the `key` attribute, with this you can add a unique identifier to a …
=> Some enhancements

resources/lang/ja/adminlte.php, resources/lang/ja/menu.php
- Added lang files for japanese localization
=> add japanese translation file.

resources/views/partials/menu-item-top-nav-left.blade.php, resources/views/partials/menu-item-top-nav.blade.php
**Fixes**
- menu items for the right topnav was shown in the left topnav too.
- hide menu header entries in topnav
=> Fix top nav

resources/views/page.blade.php
Fixed missing {{ __('adminlte::menu.profile') }}
=> Profile link is now translated

README.md, config/adminlte.php, resources/views/partials/menuitems/menu-item-sub-top-nav.blade.php, resources/views/partials/menuitems/menu-item-top-nav.blade.php, resources/views/partials/menuitems/menu-item.blade.php, src/Menu/Filters/DataFilter.php, tests/Menu/BuilderTest.php, tests/TestCase.php
I've added a new Filter called DataFilter to generate the data-attributes for any menu item.
- add DataFilter Class
- update menuitem partials
- add DataFilter in default config
- update README.md for menu item data 
Closes #519
=> Menu Item data attributes

resources/lang/zh-CN/menu.php
just a simple translation for menu.php
=> add zh-CN for menu.php

README.md, config/adminlte.php, resources/views/auth-page.blade.php, resources/views/login.blade.php, resources/views/passwords/confirm.blade.php, resources/views/passwords/email.blade.php, resources/views/passwords/reset.blade.php, resources/views/register.blade.php, resources/views/verify.blade.php
Set of improvements over the authentication views. Any help on getting these changes tested are welcome. Thanks!
**1.** Creates a new base layout (`auth-page.blade.php`) for the authentication views. This layout will be extended by the next blade files: `login.blade.php`, `register.blade.php`, `verify.blade.php`, `passwords/email.blade.php` and `passwords/reset.blade.php` of the `resources/views` folder.
The `auth-page.blade.php` looks like this:
```blade
@extends('adminlte::master')
@php( $dashboard_url = View::getSection('dashboard_url') ?? config('adminlte.dashboard_url', 'home') )
@if (config('adminlte.use_route_url', false))
@php( $dashboard_url = $dashboard_url ? route($dashboard_url) : '' )
@else
@php( $dashboard_url = $dashboard_url ? url($dashboard_url) : '' )
@endif …
```
=> Improve authentication views

README.md, resources/views/master.blade.php, resources/views/plugins.blade.php
Reworks the **master** blade layout to eliminate some sections with the same purposes:
1. Sections `load_css` and `load_js` are now removed.
2. Sections `adminlte_css_pre`, `adminlte_css` and `adminlte_js` are now available when enabling `enabled_laravel_mix` configuration option.
Please, can you give a review to these changes in order to verify it is not introducing any anomaly?
This is how the `master.blade.php` file looks now:
```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
{{-- Base Meta Tags --}}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">
{{-- Custom Meta Tags --}}
@yield('meta_tags') …
```
=> Improve the master layout

README.md, config/adminlte.php, resources/views/page.blade.php
Added ability to add extra classes to `.content-wrapper`
=> Add classes_content_wrapper option

resources/lang/tr/adminlte.php
Hello,
I've translated the new string for Turkish translation, which was missing.
Thanks,
=> Turkish translations updated

tests/AdminLteTest.php
Adds a new set of tests for all the methods inside the `src/AdminLte.php` file.
=> Set of tests for methods inside "AdminLte.php" file

resources/views/partials/navbar/menu-item-dropdown-user-menu.blade.php
Change the dropdown user menu blade file to use dropdown links instead of menu links. This solves the issue #607
=> Fix dropdown user menu to use dropdown links

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
| Question                   | Answer
| ------------------------- | ---
| Issue or Enhancement      | Enhancement
| License                   | MIT
Improve and fix spelling on the Github templates for **PRs** and **Issues.**
=> Improve the github templates for PRs and Issues.

README.md
Complete review of the **README.md** file, summary:
- Fixes the table of content to get it work for all links.
- Includes syntax highlight for all the current code blocks.
- Some sections are now better documented.
- Fixes spelling and formatting issues.
=> Improve readme format

README.md
This PR fix the example of a Laratrust menu filter in the readme.
=> fix laratrust example

README.md
Add a new step on the updating procedure relative to the package configuration file.
=> Improve readme update section

src/AdminLte.php, src/AdminLteServiceProvider.php, tests/ServiceProviderTest.php
New set of tests to get full coverage on the `AdminLteServiceProvider` class. Also, as an extra, the `AdminLte` and `AdminLteServiceProvider` classes are now documented.
[Coverage Results](https://scrutinizer-ci.com/g/jeroennoten/Laravel-AdminLTE/inspections/2589605c-cbb3-410e-8a80-19e695f1f6dc/code-structure/test-coverage)
=> Improve Service Provider Coverage

src/Menu/Builder.php, tests/Menu/BuilderTest.php
Some changes that improves the `Builder` class, summary:
- Adds code documentation to the class.
- Simplifies the logic of some class methods.
- Improves the tests for this class with new assertions and methods.
This is the [Scrutinizer Summary](https://scrutinizer-ci.com/g/jeroennoten/Laravel-AdminLTE/inspections/a59a9f4f-acff-458a-9e61-357783b2066a) for these changes. The global code quality and coverage has decreased because the implementation of some methods are simplified.
However, I will like to see this changes tested on another environment.
=> Raise Menu Builder Class Quality

README.md
=> Update Font Awesome icons link at 6.11 in README

src/AdminLte.php, src/Events/BuildingMenu.php, src/Menu/ActiveChecker.php, tests/Menu/ActiveCheckerTest.php
Improve code quality and raise coverage to `100%` on the `ActiveChecker` class among other things, summary:
- Add code documentation to the `BuildingMenu` event.
- Add minor code documentation to the `AdminLte` class.
- Add code documentation to `ActiveChecker` class and improves the code quality.
- Add more test to the `ActiveChecker` class to raise coverage up to `100%`.
[Scrutinizer Summary](https://scrutinizer-ci.com/g/jeroennoten/Laravel-AdminLTE/inspections/08092491-603b-4330-b05c-26dca25d98bb)
[Scrutinizer Coverage Changes](https://scrutinizer-ci.com/g/jeroennoten/Laravel-AdminLTE/inspections/08092491-603b-4330-b05c-26dca25d98 …
=> Improve Active Checker Class

.scrutinizer.yml
This PR migrate to new PHP Analysis of Scrutinizer.
=> Migrate to New PHP Analysis of Scrutinizer

README.md
This PR fixed the section 6.11.2 of the readme.
=> fix readme section 6.11.2

resources/views/partials/sidebar/menu-item-search-form.blade.php
This PR fix the issue #670 .
The CSRF token is not send over the form template.
=> fix issue #670

resources/lang/id/adminlte.php, resources/lang/id/menu.php
I add new translation for Bahasa Indonesia
=> Add Bahasa Indonesia Translation

README.md, config/adminlte.php, resources/views/master.blade.php
Minor improvements on the Livewire documentation and code support.
=> Improve livewire Documentation and Support

README.md
Improve and complete the documentation for all the available menu item attributes that can be configured. Also, there are some minor fixes on the redaction.
=> Improve Menu Items Documentation

.github/workflows/run-tests.yml, tests/Console/InstallTest.php, tests/Console/PluginsTest.php
This PR add Github actions / workflows.
=> add github action for tests

.github/workflows/run-tests.yml
Update the github `run-test` workflow with next changes:
- Remove installation of __sqlite3__. I consider this is was not needed, but I may be wrong, please review it.
- Add a new conditional step to upload the code coverage to `scrutinizer-ci`.
=> Update run-test workflow

.gitattributes
Update the list of `ignore-export` files and folders. These files will be ignored when generating a release version.
@lacodimizer @REJack Should we add `README.md` file and the `assets` folder into this list, or documentation should be provided within the package?
Note the assets folder contains a set of images that are used in the documentation.
=> Update Gitattributes File

README.md
- Minor update on the introduction documentation.
- Add new build passing badge from github actions.
- Add logos to existing badges.
=> Update Readme Introduction

.gitattributes, config/adminlte.php
- Update documentation links on the config file.
- Avoid exporting the `assets` folder on new package releases.
=> Update config links to new wiki pages

resources/views/components/date-range.blade.php, resources/views/components/input-file.blade.php, resources/views/components/select-bs.blade.php, resources/views/components/select2.blade.php, src/Components/DateRange.php, tests/Components/ComponentsTest.php
Improves the **Date-Range** component. Related to issue #732 :
- Component is generalized and now is able to use all configuration from [Date Range Picker](https://www.daterangepicker.com/#options). The previous implementation was restrictive in this sense.
- The component now extends from the **Input Group Component**.
=> Improve Date-Range Component

resources/views/components/button.blade.php, src/Components/Button.php
Improve the button component, label is now optional. This provides a cleaner way to make a button with only an icon.
Related to issue #732
=> Improve the button component, label is now optional.

resources/views/components/callout.blade.php, src/Components/Callout.php, tests/Components/ComponentsTest.php
Improve the **callout** component in relation to issue #732 
- Add a new `icon` attribute.
- Add a new `title-class` attribute.
- Possibility to add other attributes to the `.callout` item (like extra classes or id).
=> Improve the callout component

resources/views/components/modal.blade.php, src/Components/Modal.php, tests/Components/ComponentsTest.php
Improve the **Modal** component in relation to issue #732 
- Add several new attributes to the component (`theme`, `icon`, `static-backdrop`, `disabled-animation`, `v-centered`, and `scrollable`) 
- Add a new component slot (`footerSlot`) to enable footer customization.
=> Improve the Modal component

resources/views/components/profile-widget-item.blade.php, resources/views/components/profile-widget.blade.php, src/Components/ProfileWidget.php, src/Components/ProfileWidgetItem.php, tests/Components/ComponentsTest.php
Improve the **profile-widget** and **profile-widget-item** components in relation to issue #732 . Some new features:
- Add support to customization of the footer section.
- Add support to icons on the profile widget items.
- Add a default image when no one is provided.
=> Improve ProfileWidget and ProfileWidgetItem componets

resources/views/components/small-box.blade.php, src/Components/SmallBox.php, tests/Components/ComponentsTest.php
Improve the **small-box** component in relation to issue #732 
- Layout and attributes improvements.
- Add `Javascript` utility method to toggle the loading animation.
- Add `Javascript` utility method to help update the small box data.
=> Improve the Small Box component

resources/views/components/date-range.blade.php, resources/views/components/info-box.blade.php, resources/views/components/input-date.blade.php, resources/views/components/progress.blade.php, resources/views/components/small-box.blade.php, src/Components/InfoBox.php, tests/Components/ComponentsTest.php
Improve the Info Box component in relation to issue #732 :
- Add support to new attributes (`icon-theme`, `progress-theme`)
- Add `Javascript` utility to enable data updates.
Also, this includes some comments and typo fixes.
=> Improve the Info Box component

resources/views/page.blade.php, resources/views/partials/common/brand-logo-xs.blade.php, resources/views/partials/navbar/dropdown-item.blade.php, resources/views/partials/navbar/menu-item.blade.php, resources/views/partials/sidebar/menu-item.blade.php
Fix `@inject()` directive to inject services as strings. Related to issue #812
=> Fix @injection directive on the blade views files

config/adminlte.php
Update links due to wiki rework...
=> Update configuration file links

resources/views/partials/common/brand-logo-xl.blade.php
Fix the `@inject` directive on the `brand-logo-xl.blade.php` file in relation to issue #812 .
=> Fix inject directive on brand-logo-xl blade file

composer.json
This PR fix the adminlte version for the coming v3.1 of adminlte.
=> fix adminlte version

src/Components/Select.php, tests/Components/ComponentsTest.php
Remove the `w-100` class to fix a display issue with the new **AdminLTE v3.1.0**
=> Improve Select component to support AdminLTE 3.1

src/Components/InputGroupComponent.php, tests/Components/ComponentsTest.php
To give ability to add additional classes for input group element
=> Additional classes for input group element

resources/lang/sr/adminlte.php, resources/lang/sr/menu.php
Added Serbian Latin localization.
=> Added Serbian Latin localization.

config/adminlte.php
Update the plugins documentation link on the configuration file due to Wiki reorganization.
=> Update plugins documentation link on config file

config/adminlte.php, resources/views/partials/navbar/menu-item-fullscreen-widget.blade.php, resources/views/partials/navbar/menu-item.blade.php, src/Helpers/MenuItemHelper.php, tests/ServiceProviderTest.php
Add support to a new menu item for the navbar that implements a fullscreen widget button.
=> Add fullscreen widget button support

src/Helpers/MenuItemHelper.php
Improve usage of `isset()` in the `MenuItemHelper` class to reduce complexity of some methods.
=> Improve usage of isset() in the MenuItemHelper class

resources/views/partials/navbar/dropdown-item-link.blade.php, resources/views/partials/navbar/dropdown-item-submenu.blade.php, resources/views/partials/navbar/menu-item-dropdown-menu.blade.php, resources/views/partials/navbar/menu-item-link.blade.php, resources/views/partials/sidebar/menu-item-header.blade.php, resources/views/partials/sidebar/menu-item-link.blade.php, resources/views/partials/sidebar/menu-item-treeview-menu.blade.php
Improve usage of `@isset(...)` directive in replacement of redundant `@if(isset(...))` on some blade views.
=> Improve usage of isset() on blade views

config/adminlte.php, src/Helpers/LayoutHelper.php, tests/Helpers/LayoutHelperTest.php
- Add a new configuration option to to enable the new dark mode style available on **AdminLTE v.3.1.0**.
- Improve `LayoutHelper` code rating.
=> Add a new configuration option to enable dark mode style

config/adminlte.php
Removing the "active: true/false" from the iframe as it will have a specific page for its activation
=> removing option

resources/views/page.blade.php
=> Removed iframe

config/adminlte.php, resources/lang/en/iframe.php, resources/lang/es/iframe.php, resources/views/page.blade.php, resources/views/partials/cwrapper/cwrapper-default.blade.php, resources/views/partials/cwrapper/cwrapper-iframe.blade.php
- New configuration structure.
- Improvements on the IFrame mode blade layout.
- New language files for the IFrame blade layout.
=> Improve iframe feature support

config/adminlte.php
Add link to Iframe mode Wiki configuration
=> Update config file

src/Components/Form/SelectBs.php
=> fix: correct uppercase on extends InputGroupComponent on SelectBs

resources/views/partials/navbar/menu-item-dropdown-user-menu.blade.php, resources/views/partials/navbar/menu-item-logout-link.blade.php
Minor changes to add colours to the profile icon and the logout icon.
=> Add colours to profile and logout icons/buttons

resources/lang/en/adminlte.php, resources/lang/es/adminlte.php, resources/views/auth/login.blade.php, resources/views/auth/passwords/confirm.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/register.blade.php
| Issue or Enhancement    | Issue and Enhancement
Update authentication views with following features:
- Add hint to the **Remember me** button of the login screen.
- Add support to old submitted value for the **Remember me** button (if validation fails).
- Add the `autocomplete` property to input elements.
- Other minor improvements.
=> Update Authentication Views

resources/views/components/form/date-range.blade.php, resources/views/components/form/input-color.blade.php, resources/views/components/form/input-date.blade.php, resources/views/components/form/input-slider.blade.php, resources/views/components/form/input-switch.blade.php, resources/views/components/form/select-bs.blade.php, resources/views/components/form/select2.blade.php
| Issue or Enhancement    | Issue & Enhancement
Add fixes to some blade form components:
- `DateRange` component now has support for a placeholder.
- `DateRange` component default ranges are reviewed/fixed.
- Add edge cases checks on `DateRange` component for the old support.
- Add edge cases checks for some other components.
=> Add fixes to form components

composer.json
=> Update to use AdminLTE v3.2.0

resources/lang/de/iframe.php
Add german translation for iframe.
=> add de lang file for iframe

composer.json, resources/views/partials/cwrapper/cwrapper-iframe.blade.php
Update to use the new release of **AdminLTE v3.2.0**.
- This fix #900
=> Update to Adminlte v3.2.0

tests/Components/LayoutComponentsTest.php, tests/Components/ToolComponentsTest.php, tests/Components/WidgetComponentsTest.php
Minor reorganization of the tests for the components.
=> Reorganization of tests for components.

src/Console/PackageResources/TranslationsResource.php
Fixs the language files publishing logic to support **Laravel 9** changes.
See https://laravel.com/docs/9.x/upgrade#the-lang-directory
Fix #1069
=> Fix lang files publishing logic to support laravel 9

.github/workflows/run-tests.yml, composer.json
This PR add support for Laravel 9.
=> Add Laravel 9 support

.scrutinizer.yml, composer.json, phpunit.xml, tests/Helpers/CommandHelperTest.php, tests/Helpers/LayoutHelperTest.php
- Update required version of **phpunit** to `>=9.1.0`
- Fix warnings on the tests due to **phpunit** changes.
- Migrate configuration of **phpunit** to new format.
=> Prepare tests for phpunit 9+

config/adminlte.php, resources/views/page.blade.php, resources/views/partials/common/preloader.blade.php, src/Helpers/LayoutHelper.php, tests/Helpers/LayoutHelperTest.php
Added preloader animation as seen on [adminlte.io](https://adminlte.io/themes/v3/)
> **Note:** with a failing test: Failed asserting that directory "test-folder-copy" does not exist.
Good evening fellas. First of all thanks a lot for this package. You've solved an intern's (me) biggest problem.
This is my first ever PR. I tried to follow the guidelines as best as I could.
I had a failing test  which, I very naively think , is not a problem.  I assert myself that the folder was deleted automatically once the tests were finished.
Failed asserting that directory "test-folder-copy" does not exist.
I looked around a bit and i didn't …
=> Add preloader animation

resources/lang/fr/adminlte.php, resources/lang/fr/iframe.php, resources/lang/fr/menu.php
| Issue or Enhancement    |Enhancement
=> Added french Language (fr)translation

resources/lang/sk/adminlte.php, resources/lang/sk/iframe.php, resources/lang/sk/menu.php
Language files for Slovak translation
=> Added Slovak language translation

.editorconfig, .github/workflows/run-tests.yml
- Improve `.editorconfig` file to match latest `Laravel` conventions.
- Update the `run-tests` workflow to match the new editor config.
=> Improve editor config

resources/lang/ja/adminlte.php
change japanese translation of 'login_message' 
from ログインしてセッションを開始する to ログイン画面
=> change japanese translation of 'login_message'

resources/lang/pt-pt/adminlte.php, resources/lang/pt-pt/iframe.php, resources/lang/pt-pt/menu.php
Adding translations for (European) Portuguese
=> add pt-pt translations

src/Helpers/LayoutHelper.php, src/Helpers/MenuItemHelper.php, src/Helpers/NavbarItemHelper.php, src/Helpers/SidebarItemHelper.php
Improve some helper methods:
- Add better code style
- Fix method descriptions
- Add default values when reading config values
=> Improve some helper methods

.github/workflows/run-tests.yml, README.md, composer.json
This PR add support for Laravel 12.
=> add support for Laravel 12

docs/sections/configuration/basic_configuration.md
Just a quick change to fix a typo :)
=> Fixed typo
