- config/adminlte.php
- resources/views/master.blade.php
Added an @if directive in master.blade.php to include CDN for datatables. Pretty common usage. Added array in config 'plugins'=>['datatables'=>false] -- do not inculde by default, set to true to enable datatables in project. 
This keeps the project light but easy to add datatables to it.
> added boolean to enable datatables easily in app

- config/adminlte.php
- resources/views/master.blade.php
- src/AdminLte.php
- src/Menu/Builder.php
- tests/AdminLteTest.php
- tests/TestCase.php
Simple gate functionality when building menu. Allows to add 'permission' item to menu array and check against a configured gate.
> Add simple Gate functionality

- resources/views/partials/menu-item.blade.php
The current AdminLTE demo uses a `<span class="pull-right-container">` to wrap menu items with a label.
https://github.com/almasaeed2010/AdminLTE/blob/master/index.html#L347
> Add container to menu items with labels to fix display issue in firefox

- README.md
- src/Menu/Builder.php
- src/Menu/Filters/GateFilter.php
Now the set menu header text is on the Gate filter, but if you want to have more that one filters to a header in the menu you have to set that piece of code (see below) on the last filter, so why no add that code on the Builder.
```
if (isset($item['header'])) {
$item = $item['header'];
}
```
> Move set header menu title to the builder

- README.md
- config/adminlte.php
- resources/views/master.blade.php
To add Select2 to the project it was required to modify the vendor folder since all custom JS is loaded **after** the theme CSS/JS was loaded, this makes the Select2 to break. So added the library as a plugin so it can be optional and called **before** the theme CSS/JS is called, stopping the need of modifying the vendor's folder to use Select2.
> Select2 as a Plugin

- resources/lang/pt-br/adminlte.php
Recently started using the project (congrats by the way) and noticed that the value for the sign_in key in the pt-BR locale could be improved.
Sign In usually means that the user will make an action to "Enter" or "Access" the system, so instead of "Assinar" which would be better translated to English as "Subscribe", I changed to "Entrar", which means in English "Enter".
Also, I have noticed that the folder uses "pt-br" in all lowercase. Shouldn't it be "pt-BR"? Other packages (like this one https://github.com/caouecs/Laravel-lang) uses uppercase in the second part. I think this RFC could explain more https://tools.ietf.org/html/bcp47#section-2.2.4
> Adjusting the translation of sign_in key for pt-BR locale

- src/Menu/ActiveChecker.php
- tests/Menu/ActiveCheckerTest.php
Actual behaviour:
example.test/menu/item1?param=option doesn't trigger the active menu condition for the url example.test/menu/item1.
Fix:
example.test/menu/item1?param=option will trigger the active menu condition for the url example.test/menu/item1.
> Fix Menu Active Checker for url params

- config/adminlte.php
- resources/views/partials/menu-item.blade.php
- src/Menu/Filters/SearchFilter.php
Hello,
As reported in the issue #119, the Search menu item was missing. I created a new filter. Now we can add it as any other menu item.
**New config option documentation**
```php
[
// This option is only here to tell the system that this is a search menu item
// as we coud not rely on the 'text' value.
'search' => true,
// The "text" option is used now as value for the placeholder
'text' => 'Search...',
// Another option (not implemented) would be to create a "placeholder" option but I thought it would be more
// consistant from a configurat point of view to keep "text" (less consistant from a HTML point of view though)
// 'placeholder' => 'Search...',
// OPTIONAL
// Same as the HREF filter:
'url' => '',
// Or
'route' => '',
// Must be post or get otherwise it set to the default "get" …
```
> Add Search menu item

- README.md
- src/Menu/ActiveChecker.php
- tests/Menu/ActiveCheckerTest.php
The old version used `Str::is` which can not evaluate regex, it only has support for wildcards such as `*`.
I have edited `ActiveChecker` so that you can simply add `regex:` followed by the regex in your config file and it will proces the regex automatically.
For example:
```php
'active'  => ['/posts', 'regex:@^posts/[0-9]+$@'],
```
This will make these links active:
- /posts
- /posts/1
- /posts/65402
But not these links:
- /posts/create
- /posts/1abc
If there's any questions, please add them below :)
[Please refer to this issue.](https://github.com/jeroennoten/Laravel-AdminLTE/issues/299)
> Added regex evaluation for active menu items.

- resources/views/master.blade.php
CSS to plugin pace has been imported before from `plugins.blade.php`. This happened after the [plugins config changes](https://github.com/jeroennoten/Laravel-AdminLTE/pull/330).
> Remove unnecessary code

- README.md
- composer.json
This PR drop the support of Laravel 6. The support for Laravel 6 will be come with a new branch and version of this project.
> drop support for laravel 6

- config/adminlte.php
Current version did not have support for the bootstrap4 css files. 
This made it rather to users confusing when no styling was applied to pagination on datatables.
> Updated datatables defaults to apply bootstrap4

- resources/views/master.blade.php
Hello.
When I tried to use the laravel mix [version method](https://laravel.com/docs/6.x/mix#versioning-and-cache-busting), it could not be used because app.js and app.css were loaded by the asset method.
This PR is a modification to use the above version method.
I'd be happy if you could ask for a review.
Thank you.
> Enable laravel-mix version method

- resources/views/passwords/reset.blade.php
This PR fixes some incorrect html tags closing in  `resources/views/passwords/reset.blade.php` file.
This
```html
<div class="invalid-feedback">
<strong>{{ $errors->first('password') }}</strong>
</span>
```
Should be
```html
<div class="invalid-feedback">
<strong>{{ $errors->first('password') }}</strong>
</div>
```
> Fix incorrect html tag closing

- src/Menu/Builder.php
I'm not really sure what the impact is of this change, but in my case it seem's to fix my issue.
When you use `addIn` to add sub-menu items, the top menu item doesn't get the active class as it should.
As mentioned in issue: https://github.com/jeroennoten/Laravel-AdminLTE/issues/509
> Fix "Active" class in dynamic submenu's

- config/adminlte.php
Actually, **aqua** is not a supported `text-<color>` by AdminLTE. So this was replaced by **cyan** on the menu configuration options.
> Change menu icon color for information label on configs

- README.md
Improve the documentation of the configuration option `classes_sidebar_nav` to provide information about built-in classes that can be used.
> Improve the documentation of configuration option "classes_sidebar_nav"

- src/Console/AdminLteInstallCommand.php
A full install should be a full install, including the main views.
This PR fixes #573
> Add Main Views To Full Install

- README.md
- src/AdminLte.php
Currently, it is not possible to use a fixed navbar (top navigation) and/or a fixed footer when `layout_topnav` is enabled (set to `true`). Those restrictions are not imposed by [AdminLTE](https://adminlte.io/docs/3.0/layout.html), in its site the documentation says:
> **Note!**
> You cannot use both layout-boxed and layout-navbar-fixed or layout-footer-fixed at the same time. Anything else can be mixed together.
So, this **PR** review the logic of the method `getBodyClasses()` to make restrictions consistent with the **AdminLTE** ones.
1. Allows fixed navbar and/or fixed footer with `layout_topnav`.
2. Restricts the fixed navbar and the fixed footer with `layout_boxed`.
3. Improves the documentation to be more clear about these restrictions.
> Review the layouts restrictions

- resources/lang/en/adminlte.php
- resources/lang/es/adminlte.php
- resources/views/passwords/confirm.blade.php
1. Fixes wrong reference to variable `$register_url` on file `/resources/views/passwords/confirm.blade.php`
2. Adds a missing message (`confirm_password_message`) that is used by the previous blade file.
> Fixes on confirm password blade

- src/Menu/Builder.php
If you have multiple submenu's in submenu's, lets say:
- Gallery
- 2017
-Jan
-Feb
-March
- 2018
-Jan  <-- Crashes here
-Feb
-March
It'll give you a error about the key text not being found. This fix fixes that. (It's looking in a sub-menu, not finding the 2018 key, and thus adding a null key. The correct behavior is to continue the loop.
Code to replicate:
```            
foreach(range(2016, date('Y')) as $year) {
$event->menu->addIn('gallery', [
'text' => $year,
'key' => 'gallery_'.$year,
'icon' => 'far fa-fw fa-caret-right',
]);
foreach (range(1,12) as $month) {
$event->menu->addIn('gallery_'.$year, [
'text' => $month,
'key' => 'gallery_'.$year.'_'.$month,
'url' => route('admin.gallery.show', [$year, $month]),
'icon' => 'far fa-fw fa-caret-right',
]);
}
}`
> Fix multiple submenu's in submenu's.

- README.md
- config/adminlte.php
- resources/views/master.blade.php
Adds new configuration options related to **Laravel Mix**, in order to provide a way to change the paths related to the compiled `CSS` and `JS` files:
- **laravel_mix_css_path**
Path (including file name) to the compiled `CSS` file. This path should be relative to the public folder. Default value is `css/app.css`
- **laravel_mix_js_path**
Path (including file name) to the compiled `JS` file. This path should be relative to the public folder. Default value is `js/app.js`
> New laravel mix options for compiled JS and CSS paths

- composer.json
- tests/TestCase.php
Adds the `dev-package` **orchestra/testbench** to the composer dependencies. This package is needed for testing purposes. Also, we use `Orchestra\Testbench\TestCase` as the `BaseTestCase` class in replacement of the previous `PHPUnit\Framework\TestCase`.
> Add dev-package orchestra/testbench for testing purposes

- src/AdminLte.php
Minor fix to use the new `LayoutHelper::isLayoutTopnavEnabled()` method inside the `AdminLte` class.
> Use LayoutHelper on AdminLte class

- config/adminlte.php
- resources/views/partials/navbar/navbar-layout-topnav.blade.php
- resources/views/partials/navbar/navbar.blade.php
Changes the default value of the configuration option `classes_topnav_nav` from `navbar-expand-md` to `navbar-expand` to solve the issue #623
> Change default value for config classes_topnav_nav

- src/Console/AdminLteStatusCommand.php
Minor fix to the signature of the `adminlte:status` artisan command. With the current signature, executing the next code (inside a Laravel application context) will store `false` on the `$exists` variable, instead a `true` is expected. Note, this works as expected for the other commands (`install`, `plugins` and `update`):
```php
$commands = Artisan::all();
$exists = Arr::has($commands, 'adminlte:status');
```
> Fix Signature of adminlte:status Artisan Command.

- src/Menu/ActiveChecker.php
- tests/Menu/ActiveCheckerTest.php
- tests/TestCase.php
Fix the issue #612 
The **Active Checker** was not able to detect active menu items when `forceScheme('https')` is configured on the `UrlGenerator` instance. To give a solution to this problem, the `scheme` of the compared pattern is replaced by the wildcard `*` on the `checkPattern()` method.
Also, `Request` instance is not longer injected on the **Active Checker** constructor, instead it is obtained from the `UrlGenerator` instance.
Additional test is included to cover this issue.
> Fix Issue 612

- src/Console/AdminLteInstallCommand.php
This PR revert the PR #574 
The publishing of main views are only useful, if changes on main views are needed. But not on a full install.
Main views can be extended without publishing all main views.
> revert PR #574

- src/Menu/Builder.php
- tests/Menu/BuilderTest.php
Changes to apply, correctly, the filters on the menu items when new items are added. In particular, the `submenu_class` (from the `ClassesFilter`) attribute is not added when new items are added inside a menu item that wasn't previously a **"submenu"** item.
Related issue: #657 
Also, a new test has been added to contemplate this particular case.
> Fix Issue 657

- README.md
- src/Menu/Builder.php
- tests/Menu/BuilderTest.php
Fixs the issue #665. There was a problem when we `add()` elements on the menu using the `Builder` instance and all the items added are restricted by permissions: This problem is only present with **PHP versions below 7.3.0**, since:
> On PHP 7.3.0 the `array_push()` function can now be called with only one parameter. Formerly, at least two parameters have been required.
Also, the `Laratrust` filter example is now fixed, and a test was added to verify the explained issue.
> Fix Issue 665

- src/Menu/ActiveChecker.php
- tests/Menu/ActiveCheckerTest.php
Improve the `ActiveChecker` module to support `active` field of menu items using urls with query parameters, example:
```php
[
'text' => 'Categories',
'url'  => 'url?type=category',
'icon' => 'far fa-circle',
'active' => ['url?type=category'],
],
[
'text' => 'Tags',
'url'  => 'url?type=tag',
'icon' => 'far fa-circle',
'active' => ['url?type=tag'],
],
```
Related issue: #693
> Fix Issue 693

- README.md
- resources/views/partials/sidebar/menu-item-header.blade.php
- resources/views/partials/sidebar/menu-item.blade.php
- src/Menu/Filters/ClassesFilter.php
- tests/Menu/BuilderTest.php
Add support for a new `classes` attribute to be used on the menu items (for menu configuration). This is a generalization of the enhancement mentioned on issue #672 
New tests where added for this attribute and documentation was updated on the `README` file:
> This attribute provides a way to add custom classes to a particular menu item. The value should be a string with one or multiple class names, similar to the HTML `class` attribute. For example, you can make a colorful `HEADER` item centered on the left sidebar with the next definition:
> ```php
> [
>    'header'   => 'account_settings',
>    'classes'  => 'text-yellow …
```
> New classes attribute

- tests/Console/InstallTest.php
- tests/Console/PluginsTest.php
Fix to avoid some particular Artisan Console tests that can't be run with some versions of the Laravel framework.
> Avoid some tests that can't be run with some Laravel versions

- src/Menu/ActiveChecker.php
Improve the `ActiveChecker` class to remove whitespace (and other non-visible characters) before performing the comparison between the url pattern and the requested url. 
Related issue: #693
> Another fix for issue 693

- README.md
- resources/lang/en/menu.php
- src/Menu/Filters/LangFilter.php
- tests/Menu/BuilderTest.php
- tests/TestCase.php
Improves the recent included feature that provides support for menu items translation with parameters. Summary:
- Documentation was updated.
- Remove translation lines from file `resources/lang/en/menu.php` that are used only for testing purposes. These lines should not be available on the published language files.
- Improve the new feature testing. Lines needed for test this feature are now added dynamically using `Translator` instance.
- Improve the logic on the `LangFilter` class.
> Improve menu translations with parameters feature

- config/adminlte.php
- src/Menu/Builder.php
- tests/TestCase.php
- Improves the menu builder to early stop applying filters on a restricted menu item.
- Sets `GateFilter` as the first one to be applied.
This may raise performance a little when the menu contains multiple items with different permissions.
> Early stop applying filters on a restricted item

- resources/views/components/input-color.blade.php
- src/Components/InputColor.php
Improve the `input-color` component in relation to issue #732 :
- Now extends from the **input-group-component**.
- Provides a way to setup the plugin configuration from `php`.
- When an `addon` icon is used on the underlying `input-group`, the icon color will be automatically set.
> Improve Input-Color Component

- resources/views/plugins.blade.php
- Improve code logic on the `plugins.blade.php` file.
- The `asset` property of the plugin files is now optional. This may reduce the number of lines on the plugins configuration.
> Improve logic on the plugins blade file

- resources/views/partials/navbar/navbar-layout-topnav.blade.php
Changes the default value that will be used when configuration option `classes_topnav_nav` do not exists on the layout topnav mode. The default value should be `navbar-expand-md` as dictated on the [documentation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/7.-Layout-and-Styling-Configuration#722-admin-panel-classes):
> **classes_topnav_nav**: Extra classes for the top navigation. Classes will be added to element `nav.main-header.navbar`. When enabling `layout_topnav` the recommendation is to use `navbar-expand-md` to get items auto collapsed into a menu button on low screen sizes. Otherwise, stay with `navbar-expand` …
> Fix default value for classes_topnav_nav config

- resources/views/components/text-editor.blade.php
- src/Components/TextEditor.php
- tests/Components/ComponentsTest.php
| Issue or Enhancement  | Enhancement
Improve the **text-editor** component in relation to issue #732 
- The **text-editor** component now extends from the **input-group-component**, however the append/prepend `addon` slots are not supported.
- The `disabled` attribute now works over the plugin.
- A new `config` attribute was added to provide a way to configure the plugin from `php`.
> Improve the text-editor component

- resources/views/components/input-slider.blade.php
- src/Components/InputSlider.php
- tests/Components/ComponentsTest.php
Improve the **input-slider** component in relation to issue #732
- The component now extends from the **input-group-component**.
- A new `config` attribute is available to pass plugin configuration.
- The `disabled` attribute is now mapped correctly as a shortcut for `data-slider-enabled`.
- The slider `color` attribute is improved to change multiple elements of the plugin.
- The `value`, `step`, `max` and `min` attributes are now mapped as shortcuts for `data-slider-value`, `data-slider-step`, `data-slider-min` and `data-slider-max`.
> Improve the input-slider component

- resources/views/components/input-switch.blade.php
- src/Components/InputSwitch.php
- tests/Components/ComponentsTest.php
Improve the **input-switch** component in relation to issue #732 
- The component now extends from the **input-group-component**.
- The component now uses the **Bootstrap Switch** plugin.
- Add support to `LG` and `SM` sizes.
> Improve the input-switch component

- resources/views/components/input-date.blade.php
- src/Components/InputDate.php
- src/Console/PackageResources/PluginsResource.php
- tests/Components/ComponentsTest.php
- tests/Console/PluginsTest.php
Improve the **input-date** component in relation to issue #732 
- The component now extends from **input-group-component**.
- A new `config` attribute is added to support plugin configuration.
- `Moment` plugin is now included when installing `Tempus Dominus` with artisan command.
> Improve the input-date component

- resources/views/components/alert.blade.php
- src/Components/Alert.php
- src/Components/InputDate.php
- tests/Components/ComponentsTest.php
Improve the **alert** component in relation to issue #732 
- Add new `icon` attribute.
- Every alert theme now have a default icon associated with it.
- Now, you can add extra attributes to the alert, like `id` or additional classes using `class`.
> Improve the Alert component

- resources/views/components/progress.blade.php
- src/Components/Progress.php
- tests/Components/ComponentsTest.php
Improve the **progress** component in relation to issue #732 
- The progress now accepts an `animated` attribute that will generated animated stripes.
- The progress now accepts a `withLabel` attribute that will show the percentage on the bar.
- Javascript utility methods are now available to update the progress bar dinamically.
> Improve the progress component

- resources/views/components/card.blade.php
- src/Components/Card.php
- tests/Components/ComponentsTest.php
Improve the **card** component in relation to issue #732 
- Adds a new `icon` attribute.
- The card `theme` is reworked, and a new `theme-mode` attribute is added that accepts `full` or `outline` values.
> Improve the Card component

- resources/views/partials/common/brand-logo-xl.blade.php
Fix the `brand-logo-xl.blade.php` blade file to correctly include configuration option `classes_brand`. This way you can add extra classes to the brand link, like a background color with `bg-<color>` or change border color with `border-<color>` as examples.
Related to issue #783
> Add brand classes when using logo XL

- resources/views/components/datatable.blade.php
- src/AdminLteServiceProvider.php
- src/Components/Datatable.php
- tests/Components/ComponentsTest.php
Improves the **datatables** component in relation to issue #732 :
- Add a new `config` attribute to provide a way to make `datatables` plugin configuration.
- Add several new attributes to provide theme configuration.
- Add a new set of styled tool buttons for export the data (when enabled).
- Fix some issues with the markup.
> Improve the Datatables component

- src/Menu/Builder.php
- tests/Menu/BuilderTest.php
Fix the issue #795 related to the menu builder class. When the item is a **submenu**, we need to transform all the **child** items first. These items need to be transformed first because some of the **submenu** filters (like the `ActiveFilter`) depends on these results.
In addition, some test are created to cover these cases.
> Fix issue #795 on the menu builder

- tests/Console/CommandTestCase.php
Fix an error on the artisan command tests. The php `symlink()` method fails when trying to create a symbolic link to the **adminlte assets**. To ensure the symbolic link is created correctly, we need to create the `vendor` folder into the Laravel's testing project.
The error was detected from a build process of a recent PR, see [here](https://github.com/jeroennoten/Laravel-AdminLTE/runs/1832832388) for error details.
> Fix error on the artisan command tests

- tests/Menu/BuilderTest.php
Remove extra `,` character on function call when running tests of the **Menu Builder**. This add compatibility when running the tests with **php v7.2.13** and maybe with other versions too.
> Fix menu builder tests for php 7.2.13 compatibility

- composer.json
- src/Console/PackageResources/PluginsResource.php
- Update AdminLTE to version **3.1.0** in order to start the integration process.
- Remove **FullcalendarPlugins** from the available plugins list. These resources no longer exists on **AdminLTE v3.1.0**
> Update AdminLTE to v3.1 to start integration.

- src/Components/Select2.php
- tests/Components/ComponentsTest.php
Remove the `w-100` class to fix display issue with **AdminLTE v.3.1.0**
> Improve Select2 component for compatibility with AdminLTE v3.1

- resources/views/components/input-group-component.blade.php
- src/Components/InputDate.php
- src/Components/InputFile.php
- src/Components/InputGroupComponent.php
- src/Components/InputSwitch.php
- src/Components/Select.php
- src/Components/Select2.php
- src/Components/SelectBs.php
- tests/Components/ComponentsTest.php
| Question              | Answer
- Improve the invalid style for the components that extends the **input-group-component**
Example of the old invalid style:
Example of the new invalid style:
- Add a default `null` value for some parameters of components methods.
> Improve the invalid style for components that extend the input group

- src/Components/DateRange.php
- src/Components/Input.php
- src/Components/InputColor.php
- src/Components/InputDate.php
- src/Components/InputFile.php
- src/Components/InputSlider.php
- src/Components/InputSwitch.php
- src/Components/Select.php
- src/Components/Select2.php
- src/Components/TextEditor.php
- src/Components/Textarea.php
Propagate the new **input-group-class** attribute to all components that extends from **InputGroupComponent**.
> Propagate the new input-group-class attribute to all components

- resources/views/components/input-slider.blade.php
- resources/views/components/input-switch.blade.php
- resources/views/components/text-editor.blade.php
- src/Components/InputSlider.php
- src/Components/InputSwitch.php
- src/Components/TextEditor.php
- tests/Components/ComponentsTest.php
- Improve the invalid style for **input-switch**, **input-slider** and **text-editor** components.
- Add tests to cover these changes.
**Previously:**
**Now:**
> Improve the invalid style for input-switch and input-slider components

- resources/views/partials/sidebar/left-sidebar.blade.php
Fix a **slide-down** visual issue on the sidebar after loading page due to use `mt-2` class on the `<nav>` element inside the `.sidebar`. The issue can be seen on next video. Note how the elements on the sidebar are displaced down after the page loads, like if the `mt-2` class is applied some milliseconds after the page loads.
https://user-images.githubusercontent.com/63609705/113611028-4f65e900-9624-11eb-80ba-7de96eefd748.mp4
The problem disappear if we use `pt-2` class instead of the previous `mt-2`
> Fix slide-down visual issue on sidebar after loading

- resources/views/partials/navbar/menu-item-search-form.blade.php
- src/Menu/Filters/SearchFilter.php
- tests/Menu/BuilderTest.php
Modifications to integrate the new navbar search available in the new **AdminLTE v3.1.0**. A search icon will be displayed on the navbar:
When click on the icon, the search bar will be opened over all the navbar:
> Integrate the new navbar search provided by AdminLTE v3.1.0

- resources/views/components/alert.blade.php
- src/Components/Alert.php
- tests/Components/ComponentsTest.php
This PR fixes #859 
Changes in `alert.blade.php` ensure that:
1. If title is not defined, the h5 header with icon and title is not generated
2. Passing `title=""` generates the header with icon and empty title.
3. Passing `icon=""` does not generate the font-awesome icon element.
Change in `Alert.php` ensures that if a custom `theme` attribute is passed, it does not generate an error.
> fix issues with alert component

- resources/views/components/callout.blade.php
- resources/views/components/card.blade.php
- resources/views/components/modal.blade.php
Add `mr-2` (margin right) class to icons (when available) of the next components:
- **Modal**
- **Card**
- **Callout**
> Add margin right to icons of some components

- config/adminlte.php
- resources/views/partials/navbar/menu-item.blade.php
- resources/views/partials/sidebar/menu-item.blade.php
- src/Helpers/MenuItemHelper.php
- src/Menu/Filters/SearchFilter.php
- tests/AdminLteTest.php
Improve the new **navbar search** menu item to use a new `type` property. The `type` property will help to easy distinguish the menu items. On the future we expect to use this property on all the menu items in order to simplify recognition logic.
**IMPORTANT:**
This will introduce a minor breaking change, since the menu configuration for the navbar search should be changed to use the new `type => 'navbar-search'` property instead of the old `search => true` property.
> Improve navbar search to use a new type property

- config/adminlte.php
- resources/views/partials/navbar/menu-item-search-form.blade.php
- resources/views/partials/sidebar/menu-item-search-menu.blade.php
- resources/views/partials/sidebar/menu-item.blade.php
- src/Helpers/MenuItemHelper.php
- src/Menu/Filters/SearchFilter.php
- tests/ServiceProviderTest.php
Integration of the new sidebar search bars available in **AdminLTE v3.1.0**
- Add support to a new `'type' => 'sidebar-menu-search' ` that will automatically search on the available sidebar menu items. The required configuration example is:
```php
[
'type' => 'sidebar-menu-search',
'text' => 'Menu search',
]
```
- The legacy sidebar search is still supported with old configuration or a new one using `'type' => 'sidebar-custom-search' `. This search will submit data to the configured `url` and you need to create a **CUSTOM** controller and response to handle it. This was the previous logic for search bar (navbar or sidebar). The …
> Integrate new sidebar search bars

- resources/views/partials/sidebar/menu-item-search-menu.blade.php
The new sidebar search over the menu items do not need a `name` attribute.
> Fix sidebar menu item search

- resources/views/components/date-range.blade.php
- resources/views/components/input-color.blade.php
- resources/views/components/input-date.blade.php
- resources/views/components/input-file.blade.php
- resources/views/components/input-group-component.blade.php
- resources/views/components/input-slider.blade.php
- resources/views/components/input-switch.blade.php
- resources/views/components/input.blade.php
- resources/views/components/select-bs.blade.php
- resources/views/components/select.blade.php
- resources/views/components/select2.blade.php
- resources/views/components/text-editor.blade.php
- resources/views/components/textarea.blade.php
- src/Components/DateRange.php
- src/Components/Input.php
- src/Components/InputColor.php
- src/Components/InputDate.php
- src/Components/InputFile.php
- src/Components/InputGroupComponent.php
- src/Components/InputSlider.php
- src/Components/InputSwitch.php
- src/Components/Select.php
- src/Components/Select2.php
- src/Components/SelectBs.php
- src/Components/TextEditor.php
- src/Components/Textarea.php
- tests/Components/ComponentsTest.php
| Issue or Enhancement    | Issue and Enhancement
Improve and fix some issue on the **input-group-component** and its dependant components in relation to issue #861 
- Add support to a new **id** attribute. When not provided, the **name** attribute will be used as the **id**.
- Rename some properties of the component:
- **size** => **igroup-size** (The input group size)
- **top-class** => **fgroup-class** (The form group extra classes)
- **input-group-class** => **igroup-class** (The input group extra classes)
- Allow the specification of the **error key** to lookup for validation errors using a new **error-key** property. When not provided the property will be …
> Improves and fix issues on the input-group-component

- resources/views/components/form/date-range.blade.php
- resources/views/components/form/input-date.blade.php
- resources/views/components/widget/info-box.blade.php
- resources/views/components/widget/progress.blade.php
- resources/views/components/widget/small-box.blade.php
Currently, various **blade-x components** provides `Javascript` utilities methods to interact whit they. This PR replaces those utilities method that are registered under multiple global variables of the `window` javascript object by new utilities classes. This way, we don't need to register any global variable on `Javascript` and the user can still access the utilities using the provided new classes.
Previously, we use next code example to update an **info-box** component:
```js
$(document).ready(() => {
let data = {text: 'new text', description: 'new description'};
_adminlte_ibUtils.update('myInfoBoxID', data);
});
```
Now, we …
> Replace components javascript utility methods by classes

- config/adminlte.php
- src/Helpers/LayoutHelper.php
- tests/Helpers/LayoutHelperTest.php
Review the sidebar mini configuration options. The new supported options will be:
- `lg` to enable sidebar mini mode for desktop and bigger screens (>= 992px). Previously: `true`.
- `md` to enable sidebar mini mode for small tablet and bigger screens (>= 768px). Previously: `md`.
- `xs` to enable sidebar mini mode for extra small and bigger screens (>= 0px).
- `null` to disable the sidebar mini mode. Previously: `false`.
Also, fix a small bug that includes both `sidebar-mini` and `sidebar-mini-md` into the body classes when using the `md` option.
> Review the sidebar mini configuration options

- resources/views/components/form/date-range.blade.php
- resources/views/components/form/input-color.blade.php
- resources/views/components/form/input-date.blade.php
- resources/views/components/form/input-file.blade.php
- resources/views/components/form/input-group-component.blade.php
- resources/views/components/form/input-slider.blade.php
- resources/views/components/form/input-switch.blade.php
- resources/views/components/form/input.blade.php
- resources/views/components/form/select-bs.blade.php
- resources/views/components/form/select.blade.php
- resources/views/components/form/select2.blade.php
- resources/views/components/form/text-editor.blade.php
- resources/views/components/form/textarea.blade.php
- src/Components/Form/InputDate.php
- src/Components/Form/InputFile.php
- src/Components/Form/InputGroupComponent.php
- src/Components/Form/InputSlider.php
- src/Components/Form/InputSwitch.php
- src/Components/Form/SelectBs.php
- src/Components/Form/TextEditor.php
- tests/Components/FormComponentsTest.php
| Issue or Enhancement    | Issue & Enhancement
Make improvements on the lookup for validation errors using the session errors bag:
- The lookup logic was moved to the `InputGroupClass`, there is no need to check the errors bag on each blade template.
- Now, existence of the errors bag is checked before trying to access it.
> Improve error lookup on the session's errors bag for the components

- resources/lang/pl/adminlte.php
- resources/lang/pl/menu.php
Adding some missing Polish translations.
> Add more Polish translations

- config/adminlte.php
- resources/views/page.blade.php
- resources/views/partials/cwrapper/cwrapper-default.blade.php
- resources/views/partials/cwrapper/cwrapper-iframe.blade.php
Add base logic to support `IFrame` mode feature. To use the `IFrame` mode, the user should define his main/root view as just:
```blade
@extends('adminlte::page', ['iframeEnabled' => true])
```
All other views will be defines as before ([see usage](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Usage)):
```blade
@extends('adminlte::page')
...
...
...
```
> Add base support to iframe mode feature

- config/adminlte.php
- resources/views/partials/cwrapper/cwrapper-default.blade.php
- resources/views/partials/cwrapper/cwrapper-iframe.blade.php
- Add new configuration options for the **IFrame** mode (`auto_show_new_tab` and `use_navbar_items`).
- Enable default values for all configurations of the **IFrame** mode.
> Add new IFrame configuration options

- resources/views/partials/cwrapper/cwrapper-iframe.blade.php
Using a default `null` value for the **config helper** is not needed. The Laravel **config helper** always defaults to `null` when the key do not exists.
> Improve Iframe mode view

- config/adminlte.php
- resources/lang/en/iframe.php
- resources/lang/es/iframe.php
- resources/views/page.blade.php
- resources/views/partials/cwrapper/cwrapper-default.blade.php
- resources/views/partials/cwrapper/cwrapper-iframe.blade.php
Add base logic to support `IFrame` mode feature. To use the `IFrame` mode, the user should define his main/root view as just:
```blade
@extends('adminlte::page', ['iFrameEnabled' => true])
```
All other views will be defined as before ([see usage](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Usage)):
```blade
@extends('adminlte::page')
...
...
...
```
Also, there is a new section on the configuration file to setup the `IFrame` mode:
```php
'iframe' => [
'default_tab' => [
'url' => null,
'title' => null,
],
'buttons' => [
'close' => true,
'close_all' => true,
'close_all_other' => true,
'scroll_left' => true,
'scroll_right' => …
```
> Add support to iframe mode feature

- resources/views/components/form/options.blade.php
- src/AdminLteServiceProvider.php
- src/Components/Form/Options.php
- tests/Components/FormComponentsTest.php
The PR adds option blade component. Fixes #890
```html
<x-adminlte-select name="myoption">
<option value="">Select option...</option>
<x-adminlte-options :options="$options" selected="$selectedOption"/>
</x-adminlte-select>
<x-adminlte-select name="color">
<option value="">Select color...</option>
<x-adminlte-options :options="['r'=>'Red','b'=>'Blue','g'=>'Green']" :selected="'g'"/>
</x-adminlte-select>
<x-adminlte-select name="enabled">
<option value="">Select option...</option>
<x-adminlte-options :options="['Disabled','Enabled']" :selected="0" strict/>
</x-adminlte-select>
<x-adminlte-select name="user">
<option value="">Select …
```
> Add Options component

- src/Components/Tool/Datatable.php
- tests/Components/ToolComponentsTest.php
- Minor change to improve the underlying **Datatables** component layout to look nicely on multiple screen sizes.
- The length change tool button will not be available when `lengthChange` property of datatables is explicitly set to `false`.
> Improve datatables component layout

- resources/views/master.blade.php
Small change to favicon/manifest.json to avoid the 401 status code that results from failing to use credentials when accessing the manifest.json file when credentials are required:
Further information can be found here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
- ✅ I tested these changes.
> master.blade.php: favicons/manifest.json use-credentials

- resources/views/components/form/input-date.blade.php
- src/View/Components/Form/InputDate.php
- tests/Components/FormComponentsTest.php
Add internal `old()` support to `x-adminlte-input-date` component.
> Add old() support to x-adminlte-input-date component

- resources/views/components/form/input-date.blade.php
- resources/views/components/form/input.blade.php
- resources/views/components/form/select.blade.php
- resources/views/components/form/select2.blade.php
- resources/views/components/form/textarea.blade.php
- src/View/Components/Form/Traits/OldValueSupportTrait.php
- tests/Components/FormComponentsTest.php
Improve the base old logic for the old support on the form components:
- Review the `OldValueSupportTrait`.
- Improve old support on select components.
- Fix old support on `input-date` component to work when `allowMultidate=true` for the undelying plugin config.
> Improve base logic for old support

- resources/views/components/form/date-range.blade.php
- resources/views/components/form/input-color.blade.php
- resources/views/components/form/input-slider.blade.php
- resources/views/components/form/input-switch.blade.php
- resources/views/components/form/select-bs.blade.php
- resources/views/components/form/text-editor.blade.php
- src/View/Components/Form/DateRange.php
- src/View/Components/Form/InputColor.php
- src/View/Components/Form/InputSlider.php
- src/View/Components/Form/InputSwitch.php
- src/View/Components/Form/SelectBs.php
- src/View/Components/Form/TextEditor.php
- tests/Components/FormComponentsTest.php
Add old support for advanced form components:
- `x-adminlte-date-range`
- `x-adminlte-input-color`
- `x-adminlte-input-slider`
- `x-adminlte-input-switch`
- `x-adminlte-select-bs`
- `x-adminlte-text-editor`
This will finally fix #889
> Old support for advanced form components

- resources/views/components/form/input-group-component.blade.php
- src/View/Components/Form/InputGroupComponent.php
- tests/Components/FormComponentsTest.php
Now the errors bag can be set from the component's blade file, this enhances support for the **Livewire** package, in where the errors bag is not flashed to the session.
Fixes #972
> Improve input group component errors bag treatment

- resources/views/partials/cwrapper/cwrapper-iframe.blade.php
Change the `iframe` markup to be compatible with **AdminLTE v3.2.0**. 
Changes comes from documentation available at next link: https://adminlte.io/docs/3.2//javascript/iframe.html
> Change iframe markup to be compatible with AdminLTE 3.2.0

- resources/views/components/widget/card.blade.php
- src/View/Components/Widget/Card.php
- tests/Components/WidgetComponentsTest.php
Add multiple improvements on the `x-adminlte-card` component:
- Fix merging attributes both on the `.card` and `.card-body` elements.
- Add a new `toolsSlot` to allow adding extra tools on the card header.
- Add a new `footerSlot` to allow adding a card footer.
- Add `header-class` property to allow adding custom classes on the card header.
- Add `footer-class` property to allow adding custom classes on the card footer.
- Fixs #1052
> Improve the x-adminlte-card component

- resources/views/components/form/date-range.blade.php
Fix date range picker component when using single date mode and the placeholder option.
Date range picker is presented with a placeholder...
There is an issue when picking a single date, instead a date range is displayed on the input...
Now a single datetime is displayed on the input...
> Fix single date range picker component with placeholder

- resources/views/components/form/select-bs.blade.php
Fix invalid state visual style for the **Booststrap Select** component.
> Fix visual style on invalid state for Bootstrap Select component

- config/adminlte.php
- resources/views/master.blade.php
Currently, and by default, the **AdminLTE** panel uses some google fonts as an external resource. However, this may introduce performance issues in those environments where the internet access is restricted somehow.
This Pull Request includes a new configuration to disable the usage of external google fonts.
> New config to allow or not google fonts usage

- src/Helpers/LayoutHelper.php
php 8.2  Deprecate ${} string interpolation 
https://stitcher.io/blog/new-in-php-82#deprecate-${}-string-interpolation-rfc
> Update LayoutHelper to support PHP8.2

- config/adminlte.php
- resources/views/auth/auth-page.blade.php
Good evening, I liked the project and wanted to contribute with a small adjustment. I'm sorry! for my english, because i'm brazilian i'm still practicing.
Possibility to change the logo of the authentication pages in the configuration.
Although the framework includes a logo on the screens (login and administrative),  but for the login screen it usually appears an icon or small image representing the logo. In a situation where the developer wants to include a different logo on the login screen (example, logo adapted for screen with background dark or a larger image representing the emblem).  Also, the logo setup is more geared …
> Add feature to change the logo for authentication pages

- resources/views/plugins.blade.php
| Issue or Enhancement    | IEnhancement
Currently, when a **plugin** is not `active` by configuration (see [Plugins Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration)), you can include it on a specific blade view using the statement: `@section('plugins.PluginName', true)`.
However, when the **plugin** is `active` by configuration, it will be included in all the blade views that extends the **AdminLTE layout**, and there is no way to explicit deactivate it on a specific blade view (i.e, to not include its files on that blade view).
This **PR** address that situation by supporting explicit deactivation of a plugin that is `active` by …
> Support explicit plugin deactivation when active by default

- resources/views/components/form/date-range.blade.php
- resources/views/components/form/input-color.blade.php
- resources/views/components/form/input-date.blade.php
- resources/views/components/form/input-file.blade.php
- resources/views/components/form/input-group-component.blade.php
- resources/views/components/form/input-slider.blade.php
- resources/views/components/form/input-switch.blade.php
- resources/views/components/form/input.blade.php
- resources/views/components/form/select-bs.blade.php
- resources/views/components/form/select.blade.php
- resources/views/components/form/select2.blade.php
- resources/views/components/form/text-editor.blade.php
- resources/views/components/form/textarea.blade.php
- src/View/Components/Form/DateRange.php
- src/View/Components/Form/InputColor.php
- src/View/Components/Form/InputDate.php
- src/View/Components/Form/InputFile.php
- src/View/Components/Form/InputGroupComponent.php
- src/View/Components/Form/InputSlider.php
- src/View/Components/Form/InputSwitch.php
- src/View/Components/Form/Options.php
- src/View/Components/Form/Select2.php
- src/View/Components/Form/SelectBs.php
- src/View/Components/Form/TextEditor.php
Review compatibility with `Livewire` validations by moving manual setup of the **errors bag** from the `input-group-component` to the blade file of each form component extending the `input-group-component`.
Fix #1149
> Review Livewire validations compatibility.

- resources/views/components/form/date-range.blade.php
- resources/views/components/form/input-color.blade.php
- resources/views/components/form/input-date.blade.php
- resources/views/components/form/input-file.blade.php
- resources/views/components/form/input-slider.blade.php
- resources/views/components/form/input-switch.blade.php
- resources/views/components/form/input.blade.php
- resources/views/components/form/select-bs.blade.php
- resources/views/components/form/select.blade.php
- resources/views/components/form/select2.blade.php
- resources/views/components/form/text-editor.blade.php
- resources/views/components/form/textarea.blade.php
Add safety check on the **form components** to cover the case when the `$errors` bag variable is `undefined`, probably because the `web` middleware was not applied to the route that is rendering the blade view that is using the mentioned components.
Fix #1158
> Add safety check for when the $errors bag variable is undefined

- resources/views/master.blade.php
Fixed plugins not being loaded for **Laravel Mix** users. This **PR** enables the possibility of including extra plugins from the config file while using `Laravel Mix`. Without this, a user may end with huge compiled files to reach the same goal (note that in most cases not all the plugins are needed in all the pages).
Fix #1160
> Fixed plugins not loading when using laravel mix

- src/View/Components/Widget/InfoBox.php
- src/View/Components/Widget/Progress.php
- tests/Components/WidgetComponentsTest.php
For the `Progress` and `InfoBox` components, ensure a progress bar is always between the range `[0, 100]`.
Fix #1162
> Protect progress bar values in the widget components

- resources/views/components/form/input-file-krajee.blade.php
- src/AdminLteServiceProvider.php
- src/View/Components/Form/InputFileKrajee.php
- tests/Components/FormComponentsTest.php
Add a new **blade form component** around the [Krajee - Bootstrap File Input](https://plugins.krajee.com/file-input) plugin.
The next blade markup...
```blade
<div class="row">
<div class="col-md-4">
<x-adminlte-input-file-krajee name="kifAvatar" label="Set Profile Picture"
preset-mode="avatar"/>
</div>
</div>
```
Will render something like next...
> Add krajee file input component

- .github/workflows/run-tests.yml
- README.md
- composer.json
- phpunit.xml
- src/AdminLteServiceProvider.php
This PR drops the support for **Laravel 6**.
**Laravel 6** outdated since September 6th, 2022
(https://laravel.com/docs/9.x/releases)
> Drop support to Laravel 6

- .github/workflows/run-tests.yml
- phpunit.xml
- tests/AdminLteTest.php
> Add support for testing on Laravel 10

- resources/views/components/widget/info-box.blade.php
- src/View/Components/Widget/InfoBox.php
- tests/Components/WidgetComponentsTest.php
There is no option or attribute to add a URL in the info box component. After this pull request, it is easy to navigate any module through the info box.
Before
```
<x-adminlte-info-box title="Employees" text="10" icon="fas fa-user-friends " icon-theme="green" />
```
After
```
<x-adminlte-info-box title="Employees" text="10" url="/employees" icon="fas fa-user-friends " icon-theme="green" />
```
> Add title url in info-box component

- resources/views/master.blade.php
Fixes the bug that when using Laravel in version 10.xx.xx '@if(app()->version() >= 7)' was not being validated correctly.
> Fixing Laravel version error with Livewire

- resources/lang/ja/adminlte.php
from パスワードを記憶する to 認証状態を保持する
Fix Japanese translation of `'remember_me'`.
Fix #1212
> change japanese translation of 'remember_me'

- resources/views/components/layout/navbar-darkmode-widget.blade.php
Improve the **Dark Mode Widget** in order to add compatibility to the **IFrame Mode** of the AdminLTE template.
Fix  #1242
> Add compatibility with the IFrame mode on the DarkMode Widget

- .github/workflows/run-tests.yml
- composer.json
- tests/Components/FormComponentsTest.php
- Include **Laravel 11** and **PHP 8.3** on the tests matrix
- Update `checkout` and `cache` actions to `v4`
- Improve commentaries on the workflow
- Improve the upload code coverage step
- Remove `scrutinizer/ocular` from dev dependencies, it's instead required in the upload coverage step
- Fix tests to provide compatibility with **Laravel 11**
> Add Laravel 11 support on tests

- src/Helpers/MenuItemHelper.php
- src/Menu/Filters/GateFilter.php
- tests/AdminLteTest.php
- tests/Menu/BuilderTest.php
Improve the `Gate`  filter to also restrict **submenu items** were all its children are also restricted.
Fix #1111
> Improve Gate Filter / Fix Issue #1111

- src/Menu/ActiveChecker.php
- src/Menu/Filters/ActiveFilter.php
- src/Menu/Filters/HrefFilter.php
- tests/Menu/ActiveCheckerTest.php
- tests/Menu/BuilderTest.php
- tests/Menu/ClassesFilterTest.php
- tests/Menu/DataFilterTest.php
- tests/Menu/GateFilterTest.php
- tests/Menu/HrefFilterTest.php
- tests/Menu/SearchFilterTest.php
- tests/TestCase.php
Improve the `ActiveChecker` class:
- Internal `UrlGenerator` instance was removed, instead `url()` helper from Laravel is used now.
- Internal `Request` instance was removed, instead `request()` helper from Laravel is used now.
- Improve the logic of the class.
Improve the `HrefFilter` class:
- Internal `UrlGenerator` instance was removed, instead `url()` helper from Laravel is used now.
- Improve the internal filter logic.
Tests were modified to adapt to the previous improvements:
- The `HrefFilter` tests were separated into a different test class.
- Since the `ActiveChecker` and `HrefFilter` constructor methods were changed, most …
> Improve menu filters (last stage)

- src/Menu/Builder.php
- tests/Menu/ClassesFilterTest.php
Improve the menu builder internal logic. Previously, the menu was recompiled completely each time a call to the methods `addAfter()`, `addBefore()` and `addIn()` was performed, and the recompilation was done against an already compiled version of the menu, this was not so good at performance. Also, there were some bugs when removing an active item from a nested submenu, since the menu was not recompiled and the root submenu containing that item remainded active.
We can solve all these issues by keeping a raw (uncompiled) version of the menu internally, and with a flag to indicate that the menu needs a recompilation after issuing one …
> Improve the menu builder class

- src/Console/PackageResources/AssetsResource.php
- src/Console/PackageResources/AuthViewsResource.php
- src/Console/PackageResources/BasicRoutesResource.php
- src/Console/PackageResources/BasicViewsResource.php
- src/Console/PackageResources/ConfigResource.php
- src/Console/PackageResources/MainViewsResource.php
- src/Console/PackageResources/PluginsResource.php
- src/Console/PackageResources/TranslationsResource.php
- src/Helpers/CommandHelper.php
- tests/Console/CommandTestCase.php
- tests/Helpers/CommandHelperTest.php
- Replace own implementation of `EnsureDirectoryExists()` by the one provided by the **File facade**.
- Replace own implementation of `removeDirectory()` by the one provided by the **File facade**.
- Improve logic on `copyDirectories()`, now returns a boolean when failing. **Scrutinizer rating** is also improved.
- Improve logic on `compareDirectories()`. **Scrutinizer rating** is also improved.
- Improve testing over this class.
> Improve CommandHelper class

- resources/views/components/widget/profile-widget.blade.php
- src/View/Components/Widget/ProfileWidget.php
Allow changing the default icon that is shown when no image is provided on the `ProfileWidget` component.
> Allow changing icon on ProfileWidget component

- src/Console/AdminLteInstallCommand.php
- src/Console/AdminLtePluginCommand.php
- src/Console/AdminLteStatusCommand.php
- src/Console/AdminLteUpdateCommand.php
- tests/Console/CommandTestCase.php
- tests/Console/InstallTest.php
- tests/Console/PluginsTest.php
- tests/Console/StatusTest.php
Improve the artisan commands available on this package:
- `basic_routes` resources renamed to `auth_routes`.
- Installation of type `enhanced` was removed, and replaced by `basic_with_auth` (basic installation + resources related to **Laravel/UI**) and `basic_with_views` (basic installation + layouts views).
- The installation of type `full` now publish all the package resources.
- Logic of the command was improved.
- The resources status table now shows a new column named `Publishing Target` with the installation target folder or file for each resource.
- The style of the `Required` column was improved.
- Logic of the command was …
> Improve the artisan commands

- src/Console/PackageResources/PluginsResource.php
On the `PluginsResource` class treat `Moment.js` as an independent plugin, and use it as a dependency for other plugins like the **Date Range Picker** and **Tempus Dominus**.
This will also solve an issue that appears when you installs, for example, **Date Range Picker**. Note, the **Moment.js** will also be installed as a resource of the previous plugin. Under this situation, the plugin status entry for the **Tempus Dominus** plugin will be shown as `Mismatch` because `Moment.js` is also a resource required by it, and the implemented logic incorrectly assumes that the plugin was partially installed.
With the new implementation, …
> PluginsResource: Treat moment.js as independent plugin

- src/Console/AdminLteInstallCommand.php
- src/Console/AdminLteStatusCommand.php
- src/Console/PackageResources/BladeComponentsResource.php
- tests/Console/CommandTestCase.php
- tests/Console/InstallTest.php
Solves the issue #944 
Allow publishing the blade components of the package so the user can then customize them. Components may be published with command:
```sh
php artisan adminlte:install --only="components"
```
Once published, these customizable version of the components may be used using the `Laravel` convention for classes nested into sub-directories. For example, the customizable version of the [Input Component](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Forms-Components#input) should be used like:
```blade
<x-adminlte.form.input />
```
Instead of:
```blade
<x-adminlte-input />
```
> Allow publishing components

- src/AdminLteServiceProvider.php
- src/Console/AdminLteRemoveCommand.php
- tests/Console/RemoveTest.php
Add a new `adminlte:remove` command to allow uninstalling already published package resources.
```sh
> php artisan adminlte:remove --help
Description:
Uninstalls one or more specified resources
Usage:
adminlte:remove [options] [--] <resource>...
Arguments:
resource              The resource to uninstall: assets, config, translations, auth_views, auth_routes, main_views or components
Options:
--force           To force the uninstall procedure without warnings alerts
--interactive     To allow the uninstall process guide you through it
-h, --help            Display help for the given command. When no command is given display help for …
```
> Add new adminlte:remove command

- resources/views/page.blade.php
- resources/views/partials/navbar/navbar-layout-topnav.blade.php
- resources/views/partials/navbar/navbar.blade.php
- resources/views/partials/sidebar/right-sidebar.blade.php
- src/Helpers/LayoutHelper.php
- tests/Helpers/LayoutHelperTest.php
Fix #1140 
Changes to auto show the right sidebar when section `right_sidebar` is present on a blade file extending the layout.
Also, the section was renamed from `right-sidebar` to `right_sidebar` to keep consistency with other section names.
> [!CAUTION]
> When introducing this change on a new release, people using the `right-sidebar` section must rename it to `right_sidebar`. Also, if the views were published, they will require an update for the auto show feature to work.
> Auto show right sidebar when section is present

- config/adminlte.php
- resources/views/components/form/date-range.blade.php
- resources/views/components/form/input-color.blade.php
- resources/views/components/form/input-date.blade.php
- resources/views/components/form/input-file-krajee.blade.php
- resources/views/components/form/input-file.blade.php
- resources/views/components/form/input-slider.blade.php
- resources/views/components/form/input-switch.blade.php
- resources/views/components/form/select-bs.blade.php
- resources/views/components/form/select.blade.php
- resources/views/components/form/select2.blade.php
- resources/views/components/form/text-editor.blade.php
- resources/views/components/layout/navbar-darkmode-widget.blade.php
- resources/views/components/layout/navbar-notification.blade.php
- resources/views/components/tool/datatable.blade.php
- resources/views/master.blade.php
In config:
I changed the Laravel Mix config lines to a new patter that can be used with Vite
In that new way, the user can choose between 'mix', 'vite' and false.
In master.blade.php:
I included a switch to include the css and js files according to the config.
It is checking if the user is using the old mix config, so it is not a breaking change.
In components
I included a check to prevent scripts from running before jQuery loading finish.
**The wiki must be updated**
https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration
My tests included
- Using Mix
- Using Vite
Further tests are recommended
> Add suport to Vite

- config/adminlte.php
- routes/web.php
- tests/ServiceProviderTest.php
Fix #1026
Add support to disable the **darkmode routes** by using a new configuration option:
```php
'disable_darkmode_routes' => false,
```
You need to set the option to `true` in order to disable darkmode routes.
> Add support to disable darkmode routes

- resources/views/components/form/date-range.blade.php
- resources/views/components/form/input-color.blade.php
- resources/views/components/form/input-date.blade.php
- resources/views/components/form/input-file-krajee.blade.php
- resources/views/components/form/input-file.blade.php
- resources/views/components/form/input-slider.blade.php
- resources/views/components/form/input-switch.blade.php
- resources/views/components/form/select-bs.blade.php
- resources/views/components/form/select.blade.php
- resources/views/components/form/select2.blade.php
- resources/views/components/form/text-editor.blade.php
- resources/views/components/layout/navbar-darkmode-widget.blade.php
- resources/views/components/layout/navbar-notification.blade.php
- resources/views/components/tool/datatable.blade.php
| Pull request type       | ISSUE
A previous PR that included support to Vite (see #1308 ) added the `type="module"` attribute to the script tags of the components. This was done mainly to solve the error `$ is not a function` when including `jQuery` configuration in VITE, because VITE will loads `jQuery` asynchronously.
However, that change will cause that those scripts will be deferred execution until the `DOMContentLoaded` event of the document fires. This might cause backward compatibility issues with existing code using those components, requiring also to add the `type="module"` attribute to other scripts pushed with `@push('js')`, since otherwise the pushed scripts …
> Revert type='module' on components scripts due to backward compatibility issues

- resources/views/components/tool/datatable.blade.php
Improve the `CSS` style of [Datatables component](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Tool-Components#datatables) when using it with the [responsive extension](https://datatables.net/extensions/responsive/). As an example check next image from before and after applying this PR:
Related to #1319
> Improve style on Datatables component when using responsive extension

- resources/views/components/form/input-switch.blade.php
- src/View/Components/Form/InputSwitch.php
- tests/Components/FormComponentsTest.php
This PR allows specifying a custom value attribute when using the `<x-adminlte-input-switch>` component, which defaults to `'true'` when not specified. Examples:
```blade
{{-- The next component will submit 'true' when the switch is on --}}
<x-adminlte-input-switch name="example1"/>
{{-- The next component will submit '1' when the switch is on --}}
<x-adminlte-input-switch name="example1" value="1"/>
```
This will fix #1316 
Also a new `is-checked` attribute (of boolean type) was added to use as an alternative of the standard `checked`, to simplify the usage of the component for next situation:
```blade
{{-- Instead of next code …
```
> Improve Input Switch component

- resources/views/auth/auth-page.blade.php
Allows the authentication views for the `laravel/ui` legacy package to use the **dark-mode** configuration of the package.
Fix #1314
> Allow auth views to use dark-mode config

- resources/views/auth/auth-page.blade.php
- resources/views/auth/login.blade.php
- resources/views/auth/passwords/confirm.blade.php
- resources/views/auth/passwords/email.blade.php
- resources/views/auth/passwords/reset.blade.php
- resources/views/auth/register.blade.php
- resources/views/auth/verify.blade.php
Improve the set of authentication views that are used with the legacy `laravel/ui` package.
- Enforce usage of `@php ... @endphp` blocks.
- Enforce usage of camel case variables with php.
> Improve auth views for legacy laravel/ui

- package-lock.json
- package.json
Bump **Vitepress** (the tool used to generate the documentation) from 1.4.x to 1.6.x.
> Bump Vitepress from 1.4.x to 1.6.x

- resources/views/master.blade.php
| Pull request type       | ISSUE
Fix the `favicon` path for the meta tag **"msapplication-TileImage"**.
Fix #1341
> Fix Favicon Path for MsApplication

- docs/sections/configuration/basic_configuration.md
Added additional notes about password related routes when `use_route_url` is set to true
Extended notes for password-related routes when setting ´use_route_url´ to _true_
Minor docs update, no issues related.
> Docs: use_route_url and password routes
